CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table item
(
    id          BIGINT generated always as identity constraint item_pk primary key,
    name        VARCHAR(255) not null,
    description VARCHAR(255) not null,
    owner_id    BIGINT       not null constraint item_users_id_fk references users on update cascade on delete cascade,
    request_id  BIGINT,
    available   BIGINT
);


